# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bbc6d213ba5a581650d08e4254717038b928782fc9294c3fb2d218c998ff94b11a2b19cb46b30a5cc49aea90d1dca3d4b07a4fb0d3db3824793c8ce0ac0b5312

test:
  secret_key_base: 99af33401b90537e5b1137becd8dc65ee2e5d2e4a6e14ae1c903778bbfc1824bc29584e2371dee8876ad853332ddd5905db0b9fa364a73242ff7a4c257487ba7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
